name: Kernel Build CI

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Kernel Localversion (PixelOS,AOSP)'
        required: true
      branch:
        description: 'Out Directory Branch (fourteen,UpsideDownCake)'
        required: true

env:
  TZ: Australia/Perth
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  CHAT_ID: ${{ secrets.CHAT_ID }}
  VERSION: ${{ github.event.inputs.version }}
  BRANCH: ${{ github.event.inputs.branch }}

jobs:
  kernel-builder:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest

    steps:
      - name: Environment Initialization
        run: |
          sudo dnf install gcc clang lld repo bc flex openssl-devel wget tar zstd bsdtar file rsync zip -y
      - name: Repo Sync
        run: |
          repo init --depth=1 -u https://github.com/aosp-sunny/android_kernel_manifest.git -b master
          repo sync --no-tags --no-clone-bundle -j$(nproc --all)
      - name: GCC Build
        run: |
          sed -i s/build-user/cyberknight777/g build/_setup_env.sh
          sed -i s/ver=..*/ver=${{ env.VERSION }}/ kernel/msm-4.14/version
          build/build.sh
      - name: Push Kernel
        run: |
            git clone https://github.com/NetErnels/anykernel3 -b sunny ak3
            mkdir -p ak3/dtbs
            cp out/${{ env.BRANCH }}/dist/Image ak3
            cat out/${{ env.BRANCH }}/dist/sm6150.dtb > ak3/dtb
            cp out/${{ env.BRANCH }}/dist/dtbo.img ak3/dtbs
            cd ak3
            zip -r9 NetErnels-sunny-${{ env.VERSION }}.zip . -x ".git*" -x "README.md" -x "LICENSE" -x "*.zip"
            curl -s -X POST -F document=@"NetErnels-sunny-${{ env.VERSION }}.zip" https://api.telegram.org/bot${{ env.BOT_TOKEN }}/sendDocument -F chat_id=${{ env.CHAT_ID }} -F parse_mode="html" -F caption="CI Kernel Build for <b>Redmi Note 10 (sunny)</b> completed."
